name: impromptu
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - accelerate==1.7.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - airportsdata==20250622
      - annotated-types==0.7.0
      - anthropic==0.56.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - av==14.4.0
      - blobfile==3.0.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - compressed-tensors==0.10.2
      - contourpy==1.3.2
      - cuda-bindings==12.9.0
      - cuda-python==12.9.0
      - cycler==0.12.1
      - datasets==3.6.0
      - decorator==5.2.1
      - decord==0.6.0
      - deepseek==1.0.0
      - deepspeed==0.17.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docstring-parser==0.16
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.115.12
      - ffmpy==0.6.0
      - filelock==3.18.0
      - fire==0.7.0
      - flashinfer-python==0.2.6.post1
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.3
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - ipython==8.37.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - litellm==1.73.6
      - llamafactory==0.9.3.dev0
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lxml==6.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - modelscope==1.27.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openai==1.93.0
      - orjson==3.10.18
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - peft==0.15.2
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pooch==1.8.2
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodomex==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - rouge-chinese==1.0.3
      - rpds-py==0.26.0
      - ruff==0.11.13
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - setproctitle==1.3.6
      - sgl-kernel==0.1.7
      - sglang==0.4.7
      - shellingham==1.5.4
      - shtab==1.7.2
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sse-starlette==2.3.6
      - stack-data==0.6.3
      - starlette==0.46.2
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomlkit==0.13.3
      - torch==2.7.1
      - torch-memory-saver==0.0.8
      - torchao==0.9.0
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.3
      - triton==3.3.1
      - trl==0.9.6
      - typer==0.16.0
      - typing-extensions==4.14.0
      - tyro==0.8.14
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - xgrammar==0.1.19
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0